services:
  genio-flash:
    build: .
    image: genio-flash:ubuntu22.04
    container_name: genio-flash
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host

    working_dir: /images

    environment:
      TZ: Asia/Taipei
      PATH: /opt/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    volumes:
      - /mnt/disk3/yocto_build/gray.lin/g720/build/tmp/deploy/images/genio-720-evk:/images
      - /dev:/dev
      - /dev/bus/usb:/dev/bus/usb
      - /home/gray.lin/platform-tools:/opt/platform-tools:ro
      - genio_home:/root

    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["bash"]

volumes:
  genio_home: